name: Trigger auto deployment for container-app-54b54zoihwqg6

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-54b54zoihwqg6-AutoDeployTrigger-fb51a909-e160-4efe-b3ea-75223d15c60f.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPP54B54ZOIHWQG6_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPP54B54ZOIHWQG6_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPP54B54ZOIHWQG6_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPP54B54ZOIHWQG6_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPP54B54ZOIHWQG6_REGISTRY_PASSWORD }}
          containerAppName: container-app-54b54zoihwqg6
          resourceGroup: todonodejspgsqlgoogleauthb1d7bf7b
          imageToBuild: default/container-app-54b54zoihwqg6:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


